from datetime import date

from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.routers import recommendations
from app.routers.auth import get_current_admin
from app.schemas.recommendation import RecommendationHistoryItem


def test_public_today_recommendation_reads_existing_record_without_generation(monkeypatch) -> None:
    app = FastAPI()
    app.include_router(recommendations.router)

    async def override_database():
        yield object()

    async def read_existing(_db):
        return {
            "date": date.today(),
            "title": "Existing public recommendation",
            "type": "note",
            "reason": "Already persisted.",
            "target": None,
            "action_label": None,
            "source": None,
        }

    monkeypatch.setattr(recommendations, "read_today_recommendation", read_existing)
    app.dependency_overrides[recommendations.get_db] = override_database

    with TestClient(app) as client:
        response = client.get("/api/recommendations/today")

    assert response.status_code == 200
    assert response.json()["title"] == "Existing public recommendation"


def test_public_today_recommendation_returns_missing_without_generation(monkeypatch) -> None:
    app = FastAPI()
    app.include_router(recommendations.router)

    async def override_database():
        yield object()

    async def read_missing(_db):
        return None

    monkeypatch.setattr(recommendations, "read_today_recommendation", read_missing)
    app.dependency_overrides[recommendations.get_db] = override_database

    with TestClient(app) as client:
        response = client.get("/api/recommendations/today")

    assert response.status_code == 404


def test_administrator_generates_today_recommendation_explicitly(monkeypatch) -> None:
    app = FastAPI()
    app.include_router(recommendations.router)

    async def override_database():
        yield object()

    async def override_admin():
        return object()

    async def generate(_db):
        return {
            "date": date.today(),
            "title": "Generated by an administrator request",
            "type": "note",
            "reason": "Explicit mutation.",
            "target": None,
            "action_label": None,
            "source": None,
        }

    monkeypatch.setattr(recommendations, "generate_daily_recommendation", generate)
    app.dependency_overrides[recommendations.get_db] = override_database
    app.dependency_overrides[get_current_admin] = override_admin

    with TestClient(app) as client:
        response = client.post("/api/recommendations/today/generate")

    assert response.status_code == 201
    assert response.json()["title"] == "Generated by an administrator request"


def test_today_recommendation_generation_requires_an_administrator() -> None:
    app = FastAPI()
    app.include_router(recommendations.router)

    with TestClient(app) as client:
        response = client.post("/api/recommendations/today/generate")

    assert response.status_code == 401


def test_recommendation_history_requires_an_administrator() -> None:
    app = FastAPI()
    app.include_router(recommendations.router)

    with TestClient(app) as client:
        response = client.get("/api/recommendations/history")

    assert response.status_code == 401


def test_recommendation_history_contract_excludes_raw_context() -> None:
    assert "raw_context" not in RecommendationHistoryItem.model_fields
