"""add images to notes

Revision ID: 1119bee5a419
Revises: 0ec85724afb9
Create Date: 2026-05-30 17:55:50.167033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1119bee5a419'
down_revision: Union[str, None] = '0ec85724afb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('images', sa.JSON(), nullable=True))
    op.drop_index('idx_notes_status', table_name='notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_notes_status', 'notes', ['status'], unique=False)
    op.drop_column('notes', 'images')
    # ### end Alembic commands ###
